[package]
name = "error_margin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray-linalg = "0.16"

[dev-dependencies]
approx = "0.5"
ndarray-rand = "0.14"
proptest = "1"
rand_isaac = "0.3"
